In [1]:
import pandas as pd

import sqlite3
import os
import csv

def create_database():
    connection = sqlite3.connect('./data/advertising_data.db')
    connection.close()
create_database()

In [8]:
df = pd.read_csv('./data/Advertising.csv')

In [9]:
df

     Unnamed: 0     TV  radio  newpaper    sales
0             0  230.1   37.8      69.2  22100.0
1             1   44.5   39.3      45.1  10400.0
2             2   17.2   45.9      69.3   9300.0
3             3  151.5   41.3      58.5  18500.0
4             4  180.8   10.8      58.4  12900.0
..          ...    ...    ...       ...      ...
195         195   38.2    3.7      13.8   7600.0
196         196   94.2    4.9       8.1   9700.0
197         197  177.0    9.3       6.4  12800.0
198         198  283.6   42.0      66.2  25500.0
199         199  232.1    8.6       8.7  13400.0

[200 rows x 5 columns]

In [10]:
import pandas as pd
import sqlite3

def load_data_to_database():
    # Leer el archivo CSV y excluir la primera columna sin nombre
    df = pd.read_csv('./data/Advertising.csv', usecols=lambda column: column != 'Unnamed: 0')

    # Conectar a la base de datos SQLite
    connection = sqlite3.connect('./data/advertising_data.db')

    # Guardar el DataFrame en la tabla "advertising_data" en la base de datos
    df.to_sql('advertising_data', connection, index=False, if_exists='append')

    # Cerrar la conexión con la base de datos
    connection.close()

load_data_to_database()